---
- name: Manage attributes configurations in iDRAC
  hosts: idrac
  gather_facts: false
  vars_files:
    - ../vars_files/credentials.yml
  vars:
    - system_attributes:
        ServerOS.1.HostName: demohostname
  roles:
    - dellemc.openmanage.idrac_attributes
