---
- name: Manage boot configurations in iDRAC
  hosts: idrac
  gather_facts: false
  vars_files:
    - ../vars_files/credentials.yml
    - ../vars_files/boot.yml
  roles:
    - dellemc.openmanage.idrac_boot

