---
- name: Operating System Deployment in iDRAC
  hosts: idrac
  gather_facts: false
  become: true
  vars_files:
    - ../vars_files/credentials.yml
    - ../vars_files/osd.yml
  roles:
    - dellemc.openmanage.idrac_os_deployment
