---
- name: Firmware update using DUP file
  hosts: idrac_131
  gather_facts: false
  vars_files:
    - ../vars_files/credentials.yml
  vars:
    - image_uri: "{{ repo_url }}"
    - transfer_protocol: "{{ transfer_protocol }}"
  roles:
    - dellemc.openmanage.redfish_firmware
